name = "gpa-calculator"
compatibility_date = "2024-02-11"

[build]
command = "pip install -r requirements.txt && python app.py"

[site]
bucket = "./templates"

[build.upload]
format = "service-worker"
