name = "gpa-calculator"
compatibility_date = "2024-02-11"

[build]
command = "pip install -r requirements.txt"
pages_build_output_dir = "templates"

[site]
bucket = "./templates"
entry-point = "workers-site"

[env.production]
name = "gpa-calculator-prod"
